@extends('layouts.app')
@section('body')
<div class="min-h-screen lg:flex">
    <aside class="no-print hidden w-72 shrink-0 flex-col bg-[#10243e] p-7 text-white lg:flex">
        <a href="{{ route('admin.orders.index') }}" class="flex items-center gap-3 text-xl font-black tracking-tight"><span class="grid h-10 w-10 place-items-center rounded-2xl bg-cyan-400 text-[#10243e]">KL</span> Kang Laundry</a>
        <div class="mt-16 text-xs font-bold uppercase tracking-[.2em] text-cyan-200">Workspace</div>
        <nav class="mt-4 space-y-2"><a class="flex items-center gap-3 rounded-xl bg-white/10 px-4 py-3 font-semibold text-cyan-200" href="{{ route('admin.orders.index') }}">◈ <span>Pesanan aktif</span></a><a class="flex items-center gap-3 rounded-xl px-4 py-3 text-slate-300 hover:bg-white/10" href="{{ route('track') }}">⌁ <span>Tracking publik</span></a></nav>
        <div class="mt-auto rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300"><div class="mb-2 text-cyan-300">Tarif saat ini</div><strong class="text-2xl text-white">Rp {{ number_format(config('laundry.rate'), 0, ',', '.') }}</strong><span> / kg</span></div>
    </aside>
    <main class="min-w-0 flex-1">
        <header class="no-print border-b border-slate-200 bg-white px-5 py-5 sm:px-8"><div class="mx-auto flex max-w-7xl items-center justify-between"><div><p class="text-sm font-bold text-cyan-600">{{ now()->translatedFormat('l, d F Y') }}</p><h1 class="mt-1 text-2xl font-black tracking-tight text-[#10243e] sm:text-3xl">Ringkasan pesanan</h1></div><a href="{{ route('admin.orders.create') }}" class="rounded-xl bg-cyan-500 px-4 py-3 text-sm font-extrabold text-white shadow-lg shadow-cyan-500/20 transition hover:bg-cyan-600">+ Pesanan baru</a></div></header>
        <div class="mx-auto max-w-7xl space-y-7 p-5 sm:p-8">
            @if(session('success')) <div class="no-print rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('success') }}</div> @endif
            <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl bg-[#10243e] p-5 text-white"><p class="text-sm text-slate-300">Total ditampilkan</p><p class="mt-3 text-3xl font-black">{{ $orders->total() }}</p></div><div class="rounded-2xl border border-cyan-100 bg-cyan-50 p-5"><p class="text-sm font-semibold text-cyan-700">Tarif / kilogram</p><p class="mt-3 text-3xl font-black text-[#10243e]">Rp 10.000</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm font-semibold text-slate-500">Status operasional</p><p class="mt-3 text-3xl font-black text-emerald-600">Online</p></div></div>
            <section class="rounded-2xl border border-slate-200 bg-white shadow-sm">
                <form class="no-print flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row" method="GET"><input name="search" value="{{ $search }}" placeholder="Cari nama atau ID pesanan..." class="min-w-0 flex-1 rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-sm focus:border-cyan-500 focus:ring-cyan-500"><select name="status" class="rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-sm"><option value="">Semua status</option>@foreach(config('laundry.statuses') as $key => $label)<option value="{{ $key }}" @selected($status === $key)>{{ $label }}</option>@endforeach</select><button class="rounded-xl bg-[#10243e] px-5 py-3 text-sm font-bold text-white">Filter</button></form>
                <div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-4">Pesanan</th><th class="px-5 py-4">Pelanggan</th><th class="px-5 py-4">Berat</th><th class="px-5 py-4">Total</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($orders as $order)<tr class="hover:bg-cyan-50/30"><td class="px-5 py-4"><div class="font-black text-[#10243e]">{{ $order->order_code }}</div><div class="mt-1 text-xs text-slate-400">{{ $order->created_at->format('d M Y, H:i') }}</div></td><td class="px-5 py-4"><div class="font-bold">{{ $order->customer_name }}</div><div class="text-xs text-slate-400">+{{ $order->whatsapp_number }}</div></td><td class="px-5 py-4 font-semibold">{{ $order->weight }} kg</td><td class="px-5 py-4 font-black">Rp {{ number_format($order->total_price, 0, ',', '.') }}</td><td class="px-5 py-4"><form method="POST" action="{{ route('admin.orders.status', $order) }}">@csrf @method('PATCH')<select name="status" onchange="this.form.submit()" class="rounded-lg border-cyan-100 bg-cyan-50 py-2 text-xs font-bold text-cyan-800">@foreach(config('laundry.statuses') as $key => $label)<option value="{{ $key }}" @selected($order->status === $key)>{{ $label }}</option>@endforeach</select></form></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><button type="button" onclick="notifyCustomer('{{ $order->whatsapp_number }}','{{ $order->customer_name }}','{{ $order->order_code }}','{{ $order->status_label }}','{{ optional($order->estimated_ready_at)->format('d M Y, H:i') ?? 'akan diinformasikan' }}')" class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 hover:bg-emerald-100">WA</button><a href="{{ route('admin.orders.receipt', $order) }}" target="_blank" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">Nota</a><form method="POST" action="{{ route('admin.orders.destroy', $order) }}" onsubmit="return confirm('Arsipkan pesanan ini?')">@csrf @method('DELETE')<button class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-600">Arsip</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-5 py-16 text-center text-slate-400">Belum ada pesanan yang cocok.</td></tr>@endforelse</tbody></table></div>
                <div class="no-print border-t border-slate-100 p-4">{{ $orders->links() }}</div>
            </section>
        </div>
    </main>
</div>
@endsection
@push('scripts')<script>function notifyCustomer(phone,name,code,status,ready){const message=`Halo ${name}, update pesanan ${code}: status saat ini ${status}. Estimasi siap: ${ready}. Terima kasih, Kang Laundry.`;window.open(`https://wa.me/${phone.replace(/\D/g,'')}?text=${encodeURIComponent(message)}`,'_blank');}</script>@endpush
